# Default values for demo-java-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.apps.ocp4-8.infocepo.com/ministere-interieur-plec/app-java-forge-dso-demo
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "master"

imagePullSecrets: 
  - name: "quay-image-pull-secret"
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  secret:
    enabled: true
  host: plec-demo.dev.numerique-interieur.com

resources: 
  limits:
    memory: "512Mi"
    cpu: "500m"  
  requests:
    memory: "512Mi"
    cpu: "500m"  

global: 
  postgresql:
    auth:
      postgresPassword: "MySupErPaSSwOrd"
      username: "userdemo"
      password: "passworddemo"
      database: "demodb"

# Contrainte de sécurité Openshift
postgresql:
  fullnameOverride: postgres-demo
  volumePermissions:
    enabled: false
    securityContext:
      runAsUser: "auto"
  securityContext:
    enabled: false
  shmVolume:
    chmod:
      enabled: false
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  primary:
    volumePermissions:
      enabled: false
      securityContext:
        runAsUser: "auto"
    securityContext:
      enabled: false
    shmVolume:
      chmod:
        enabled: false
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
